import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { homePage, migrationPage, newTechnologyPages, enrichExistingService } from './editorial.mjs';

const config = JSON.parse(await readFile(new URL('../site.config.json', import.meta.url), 'utf8'));
const design = config.design || 'modern';
if (!['modern', 'editorial'].includes(design)) throw new Error('Design inconnu.');
const themeStylesheet = design === 'editorial' ? '/proposal-b.css' : '/modern.css';
const origin = new URL(config.origin);
if (origin.protocol !== 'https:' || origin.pathname !== '/' || origin.search || origin.hash || origin.username || origin.password) throw new Error('L’origine doit être une URL HTTPS sans chemin ni identifiants.');
if (config.googleAnalyticsId && !/^G-[A-Z0-9]+$/.test(config.googleAnalyticsId)) throw new Error('Identifiant GA4 invalide.');
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const services = [
  {slug:'developpement-windev',name:'WinDev',label:'Logiciels métier',title:'Un logiciel qui suit votre façon de travailler.',description:'Développement WinDev sur mesure : des applications métier adaptées à vos usages, à vos données et aux contraintes de votre entreprise.',intro:'Votre activité a ses propres règles. Votre logiciel doit les comprendre. Nous concevons des applications WinDev autour de vos processus, pour faciliter le travail quotidien de vos équipes.',needs:['Centraliser des informations dispersées entre plusieurs outils.','Adapter une application aux spécificités de votre métier.','Faire évoluer un logiciel à mesure que vos besoins changent.'],detail:'Le point de départ : vos utilisateurs, leurs tâches et les informations dont ils ont besoin. Ensemble, nous définissons le périmètre de l’application et les priorités de développement, avant de travailler sur les écrans et les fonctionnalités.'},
  {slug:'developpement-webdev',name:'WebDev',label:'Applications web',title:'Vos outils métier, accessibles sur le Web.',description:'Conception et évolution d’applications WebDev pour les entreprises : partage des informations, outils métier et accès depuis un navigateur.',intro:'Donnez à vos collaborateurs un accès à leurs outils depuis un navigateur. Nous développons des applications WebDev adaptées aux usages de votre organisation.',needs:['Rendre une application accessible à plusieurs équipes.','Partager les informations utiles à votre activité.','Construire un outil web autour d’un processus métier.'],detail:'Un projet web commence par des choix concrets : qui utilise l’application, quelles informations sont partagées et quels accès sont nécessaires. Nous cadrons ces usages pour construire une solution cohérente avec votre organisation.'},
  {slug:'developpement-windev-mobile',name:'WinDev Mobile',label:'Applications mobiles',title:'Le bon outil, là où le travail se fait.',description:'Développement WinDev Mobile pour vos applications métier : des parcours adaptés aux équipes et à leurs usages sur le terrain.',intro:'Sur le terrain, une application doit aller à l’essentiel. Nous concevons des applications métier mobiles pour les situations réelles de vos utilisateurs.',needs:['Saisir des informations au moment où elles sont disponibles.','Consulter les données utiles lors d’un déplacement.','Relier les usages mobiles au système d’information existant.'],detail:'Les conditions d’utilisation déterminent les choix techniques : appareils, connectivité, données et fréquence des échanges. Nous clarifions ces contraintes dès le cadrage pour concevoir des parcours adaptés au terrain.'}
];
const contactLink = '<a class="button" href="/contact/">Parlons de votre projet <span aria-hidden="true">↗</span></a>';
const header = `<a class="skip" href="#contenu">Aller au contenu</a><header><a class="brand" href="/" aria-label="Serial Coders — accueil"><img src="/logo.png" width="110" height="85" alt="Serial Coders"></a><nav aria-label="Navigation principale"><a href="/#domaines">Expertises</a><a href="/migration-applications-pcsoft/">Migration</a><a href="/#societe">La société</a><a class="nav-contact" href="/contact/">Votre projet <span aria-hidden="true">↗</span></a></nav></header>`;
const footer = `<footer><div class="footer-main"><div><strong>SERIAL CODERS</strong><p>Des logiciels conçus autour de votre métier.</p></div><div><a href="mailto:contact@serialcoders.fr" data-event="contact_email_click">contact@serialcoders.fr</a><a href="tel:+33663686865" data-event="contact_phone_click">+33 (0)6 63 68 68 65</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Serial Coders</span><a href="/confidentialite/">Confidentialité</a><button type="button" id="cookie-settings">Gérer les cookies</button></div></footer><section id="consent" class="consent" aria-labelledby="consent-title" hidden><div><h2 id="consent-title">Mesure d’audience</h2><p>Avec votre accord, Google Analytics nous aide à comprendre les visites et les clics de contact. Votre choix peut être modifié à tout moment.</p></div><div class="consent-actions"><button type="button" data-consent="denied">Refuser</button><button type="button" data-consent="granted">Accepter</button></div></section><script src="/config.js" defer></script><script src="/site.js" defer></script>`;
const pages = [{path:'/', ...homePage},
...services.map(s=>({path:`/${s.slug}/`,title:`Développement ${s.name} sur mesure | Serial Coders`,description:s.description,body:`<section class="detail-hero"><a class="back" href="/#domaines">← Toutes les expertises</a><div class="eyebrow">DÉVELOPPEMENT ${s.name.toUpperCase()}</div><h1>${s.title}</h1><p class="lead">${s.intro}</p>${contactLink}</section><section class="section detail-grid"><div><span class="eyebrow">VOS BESOINS</span><h2>Une application pensée<br>pour vos usages.</h2></div><ul class="needs">${s.needs.map(n=>`<li>${n}</li>`).join('')}</ul></section><section class="section company"><h2>Commençons par<br>les bonnes questions.</h2><div><p class="large">${s.detail}</p><p>Vous disposez déjà d’une application ${s.name} ? Décrivez son fonctionnement et les évolutions souhaitées pour que nous puissions étudier votre besoin.</p></div></section><section class="contact-band"><h2>Parlons de votre application ${s.name}.</h2>${contactLink}</section>`})),
{path:'/contact/',title:'Parlons de votre projet logiciel | Serial Coders',description:'Contactez Serial Coders pour votre application sur mesure ou sa migration. Une expertise PC SOFT et multitechnologie au service de vos objectifs.',body:`<section class="detail-hero"><span class="eyebrow">VOTRE PROJET COMMENCE ICI</span><h1>Qu’aimeriez-vous<br><em>faire avancer ?</em></h1><p class="lead">Une nouvelle application, un logiciel à faire évoluer ou une migration à préparer : échangeons sur votre besoin et les technologies les plus adaptées.</p><div class="contact-options"><a class="button" href="mailto:contact@serialcoders.fr?subject=Projet%20logiciel%20%E2%80%94%20Serial%20Coders" data-event="contact_email_click">Écrire à Serial Coders ↗</a><a class="phone" href="tel:+33663686865" data-event="contact_phone_click">+33 (0)6 63 68 68 65</a></div><p>contact@serialcoders.fr</p></section><section class="section detail-grid"><div><h2>Pour préparer<br>notre premier échange.</h2><p>France et projets internationaux.</p></div><ul class="needs"><li>Votre activité et les personnes qui utiliseront l’application.</li><li>Vos technologies actuelles, leurs versions et les difficultés rencontrées.</li><li>Le résultat attendu, le nombre d’utilisateurs, vos contraintes et votre calendrier.</li></ul></section>`},
{path:'/confidentialite/',title:'Confidentialité et cookies | Serial Coders',description:'Informations sur les contacts et les préférences de mesure d’audience du site Serial Coders.',body:`<section class="section legal"><h1>Confidentialité<br>et cookies</h1><h2>Prendre contact</h2><p>Les liens de contact ouvrent votre messagerie ou votre application téléphonique. Ce site ne contient pas de formulaire de collecte. Pour toute question sur les informations communiquées lors d’un échange, écrivez à <a href="mailto:contact@serialcoders.fr">contact@serialcoders.fr</a>.</p><h2>Mesure d’audience</h2><p>${config.googleAnalyticsId ? 'Google Analytics est configuré pour mesurer les visites et les clics sur les liens de contact uniquement après votre accord. Aucune fonction publicitaire n’est activée. Les messages et coordonnées que vous adressez à Serial Coders ne sont pas transmis par ce suivi.' : 'La mesure d’audience Google Analytics n’est pas activée sur cette version du site.'}</p><h2>Votre choix</h2><p>Lorsque la mesure d’audience est disponible, vous pouvez l’accepter ou la refuser. Le lien « Gérer les cookies » permet de changer votre choix. Cette préférence est conservée dans votre navigateur pendant six mois. Sans accès au stockage du navigateur, elle s’applique seulement à la page en cours.</p></section>`}];
await mkdir('dist', {recursive:true});
pages.push(migrationPage, ...newTechnologyPages);
for (const initialPage of pages) {
  const page = enrichExistingService(initialPage);
  page.body = page.body.replace(/(<figure class="architecture-figure hero-visual">[^]*?)loading="lazy"/, '$1loading="eager" fetchpriority="high"');
  if (design === 'editorial') {
    page.body = page.body.replaceAll('/migration-architecture.png', '/migration-gold-light.png');
    if (page.path === '/migration-applications-pcsoft/') {
      // Move the illustration to a wide introductory band instead of repeating it.
      page.body = page.body.replace(/<figure class="architecture-figure[^]*?<\/figure>/, '');
      page.body = page.body.replace('</section>', '<figure class="proposal-panorama"><img src="/migration-gold-light.png" width="1536" height="1024" alt="Illustration conceptuelle de structures blanches reliées par des passerelles dorées." decoding="async"></figure></section>');
    }
  }
  const url = new URL(page.path, origin).href;
  const schema = {'@context':'https://schema.org','@type':'Organization',name:'Serial Coders',url:origin.origin,email:'contact@serialcoders.fr',telephone:'+33663686865'};
  const html = `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(page.title)}</title><meta name="description" content="${escape(page.description)}"><meta name="robots" content="${config.production ? 'index, follow' : 'noindex, nofollow'}"><link rel="canonical" href="${escape(url)}"><meta property="og:type" content="website"><meta property="og:locale" content="fr_FR"><meta property="og:title" content="${escape(page.title)}"><meta property="og:description" content="${escape(page.description)}"><meta property="og:url" content="${escape(url)}">${config.googleSiteVerification ? `<meta name="google-site-verification" content="${escape(config.googleSiteVerification)}">` : ''}<link rel="icon" href="/logo.png"><link rel="stylesheet" href="/fonts/fonts.css"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/editorial.css"><link rel="stylesheet" href="${themeStylesheet}"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body>${header}<main id="contenu">${page.body}</main>${footer}</body></html>`;
  const directory = `dist${page.path}`;
  await mkdir(directory, {recursive:true});
  await writeFile(`${directory}index.html`, html);
}
await writeFile('dist/config.js', `window.SERIAL_CODERS_CONFIG = ${JSON.stringify({googleAnalyticsId:config.googleAnalyticsId})};\n`);
await writeFile('dist/robots.txt', config.production ? `User-agent: *\nAllow: /\nSitemap: ${origin.origin}/sitemap.xml\n` : 'User-agent: *\nDisallow: /\n');
await writeFile('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p=>`<url><loc>${escape(new URL(p.path,origin).href)}</loc></url>`).join('')}</urlset>`);
await writeFile('dist/404.html', `<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page introuvable | Serial Coders</title><meta name="robots" content="noindex"><link rel="stylesheet" href="/fonts/fonts.css"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/editorial.css"><link rel="stylesheet" href="${themeStylesheet}"><main class="detail-hero"><h1>Cette page<br>n’existe pas.</h1><a class="button" href="/">Revenir à l’accueil</a></main></html>`);
console.log(`${pages.length} pages générées — ${config.production ? 'production indexable' : 'préproduction non indexable'}.`);
