// Commercial copy stays separate from the HTML document builder so the positioning
// can evolve without changing analytics, consent or deployment configuration.
const action = (label = 'Parlons de votre projet') => `<a class="button" href="/contact/">${label} <span aria-hidden="true">↗</span></a>`;
const migrationAction = '<a class="text-link" href="/migration-applications-pcsoft/">Comprendre notre accompagnement migration <span aria-hidden="true">↗</span></a>';
const partner = '<img class="partner-logo" src="/pcsoft-partner.png" width="250" height="68" loading="lazy" alt="PC SOFT — Gold Partner">';
const figure = (className = '') => `<figure class="architecture-figure ${className}"><img src="/migration-code.png" width="2060" height="763" alt="Migration du code et des données d’une application métier vers une interface modernisée." decoding="async" loading="lazy"><figcaption>Préserver la logique métier. Faire évoluer l’architecture.</figcaption></figure>`;
const migrationSteps = [
  ['Comprendre l’existant', 'Code, données, règles métier, interfaces et usages : nous identifions ce qui fait fonctionner votre application, y compris les dépendances peu visibles.', 'Une cartographie du périmètre et des points de vigilance.'],
  ['Comparer les trajectoires', 'Maintien, modernisation ciblée ou migration : nous rapprochons les besoins fonctionnels, les contraintes d’exploitation et les coûts de chaque scénario.', 'Une cible technique et une feuille de route à arbitrer.'],
  ['Valider sur un périmètre pilote', 'Un premier module permet de confronter la nouvelle architecture à vos données, aux interfaces existantes et à des situations métier représentatives.', 'Des résultats de validation avant d’élargir la migration.'],
  ['Migrer et accompagner', 'La reprise des données, la recette avec vos équipes et les conditions de bascule sont préparées ensemble. Une coexistence temporaire peut être étudiée.', 'Un plan de déploiement, de retour arrière et de transmission.']
];
const steps = () => `<ol class="migration-steps">${migrationSteps.map(([title, text, output], index) => `<li><span class="step-number">0${index + 1}</span><div><h3>${title}</h3><p>${text}</p><p class="deliverable"><strong>Objectif :</strong> ${output}</p></div></li>`).join('')}</ol>`;
const faq = entries => `<div class="faq-list">${entries.map(([question, answer]) => `<details><summary>${question}</summary><p>${answer}</p></details>`).join('')}</div>`;
const migrationFaq = [
  ['Faut-il obligatoirement réécrire toute l’application ?', 'Non. Un audit peut conduire à conserver l’application, à moderniser certaines fonctions ou à reconstruire un périmètre plus large. Une réécriture complète n’est pertinente que si son intérêt est établi au regard des coûts, des risques et de la durée de vie attendue.'],
  ['Peut-on conserver les données et les règles métier ?', 'Leur préservation fait partie des objectifs de l’étude. Elle suppose de comprendre le modèle de données, les traitements, les historiques et les interfaces. Des contrôles de reprise et des scénarios de recette permettent de vérifier le résultat ; il ne s’agit pas d’une simple traduction de code.'],
  ['Comment choisir les technologies cibles ?', 'C#, JavaScript ou d’autres technologies : le choix dépend des usages, des postes ou navigateurs visés, des interfaces, des compétences de maintenance et des contraintes d’hébergement. Nous comparons ces critères avec vous avant de retenir une architecture ; un projet peut aussi combiner plusieurs technologies.'],
  ['Une migration réduit-elle automatiquement les coûts ?', 'Non. Les licences ne représentent qu’une partie du coût total. Il faut aussi considérer la réécriture, les tests, l’hébergement, les composants tiers, la maintenance, la formation et l’exploitation. Les conditions applicables à votre installation et à la solution cible doivent être examinées avant de conclure à une économie.'],
  ['Pouvez-vous encore développer avec les outils PC SOFT ?', 'Oui. Serial Coders est partenaire Gold PC SOFT et continue à développer et faire évoluer des applications WinDev, WebDev et WinDev Mobile. Cette connaissance de l’environnement d’origine complète notre expertise multitechnologie, notamment en C# et JavaScript, pour accompagner vos choix.'],
  ['Peut-on migrer tout en continuant à utiliser l’application ?', 'Une migration progressive avec coexistence peut être envisagée, selon les interfaces et la façon dont les données sont partagées. L’étude précise ce qui est réalisable, les synchronisations nécessaires et les éventuelles fenêtres d’interruption. Nous ne promettons pas une bascule sans interruption avant cette analyse.']
];

const databaseSection = `<section class="section database-section" id="bases-de-donnees" aria-labelledby="database-title">
  <div class="section-heading"><span class="eyebrow">04 / BASES DE DONNÉES</span><h2 id="database-title">Vos données, au cœur<br>de votre application.</h2><p>Une application métier repose aussi sur la qualité de ses données. Nous maîtrisons HFSQL et de nombreux systèmes de gestion de bases de données relationnelles (SGBDR), pour construire votre projet ou faire évoluer son architecture.</p></div>
  <div class="database-grid">
    <article class="database-preferred"><span class="eyebrow">NOTRE MOTEUR DE PRÉDILECTION</span><h3>PostgreSQL<span aria-hidden="true">↗</span></h3><p>Nous privilégions PostgreSQL pour ses performances, la richesse de ses fonctionnalités intégrées et son modèle open source, sans coût de licence.</p>
      <ul class="database-benefits"><li><strong>Des performances adaptées à vos usages</strong><span>Un modèle de données, des index et des requêtes pensés pour les traitements de votre application.</span></li><li><strong>Des fonctionnalités intégrées</strong><span>Transactions, contraintes d’intégrité et prise en charge de données JSON : des outils pour répondre à des besoins métier variés.</span></li><li><strong>Sans coût de licence du moteur</strong><span>La licence PostgreSQL autorise l’utilisation sans redevance, y compris en entreprise. L’hébergement, la maintenance et l’exploitation restent à prévoir.</span></li></ul>
      <a class="text-link" href="https://www.postgresql.org/about/licence/">Consulter la licence PostgreSQL ↗</a>
    </article>
    <div class="database-engines"><span class="eyebrow">UNE EXPERTISE MULTIMOTEUR</span><h3>Le bon moteur<br>pour votre contexte.</h3><dl><div><dt>HFSQL</dt><dd>La base de données propriétaire de PC SOFT, que nous maîtrisons dans le cadre de vos applications et de leur évolution.</dd></div><div><dt>SQL Server · Oracle · MySQL</dt><dd>Des moteurs que nous maîtrisons également, pour développer autour de votre environnement et de vos contraintes.</dd></div><div><dt>Et d’autres SGBDR</dt><dd>Notre expertise ne se limite pas à cette liste. Le choix tient compte de votre existant, de vos usages et des conditions d’exploitation.</dd></div></dl></div>
  </div>
  <div class="database-project"><div><h3>Faire évoluer le moteur.<br>Préserver la valeur des données.</h3><p>Conception du modèle, optimisation des accès ou migration : nous relions les choix de base de données aux besoins de votre application. Une reprise implique de préparer les correspondances, de contrôler la cohérence des données et de valider les traitements métier.</p></div>${action('Parlons de vos données')}</div>
</section>`;

export const homePage = {
  title: 'Applications sur mesure & migration WinDev | Serial Coders',
  description: 'Partenaire Gold PC SOFT, Serial Coders développe vos applications métier et accompagne leur migration vers des technologies adaptées à vos besoins. France et international.',
  body: `<section class="hero hero-repositioned">
    <div class="hero-copy"><span class="eyebrow">APPLICATIONS MÉTIER · DÉVELOPPEMENT · MIGRATION</span>
      <h1>Votre logiciel métier.<br><em>Libre d’évoluer.</em></h1>
      <p class="lead">Du développement sur mesure à la migration de vos applications, nous faisons le lien entre votre métier, votre existant et vos prochaines ambitions.</p>
      <p class="hero-expertise">La maîtrise de WinDev, WebDev et WinDev Mobile.<br>Une expertise multitechnologie, notamment en C# et JavaScript.</p>
      <div class="hero-actions">${action()}<a class="secondary-button" href="/migration-applications-pcsoft/">Étudier une migration</a></div>
    </div>${figure('hero-visual')}
    <div class="hero-meta"><span>PARTENAIRE GOLD PC SOFT</span><span>TOUS SECTEURS D’ACTIVITÉ</span><span>FRANCE & INTERNATIONAL</span></div>
  </section>
  <section class="section" id="domaines"><div class="section-heading"><span class="eyebrow">01 / VOTRE PROJET</span><h2>Construire, faire évoluer<br>ou changer de technologie.</h2><p>Vos enjeux ne s’arrêtent pas au choix d’un langage. Nous vous accompagnons dans la conception de vos outils, leur évolution et les décisions qui engagent leur avenir.</p></div>
    <div class="offer-grid">
      <article><span class="number">01 / CRÉATION</span><h3>Développer votre application métier</h3><p>Remplacer des fichiers dispersés, structurer un processus ou créer un service interne : nous concevons une application autour des usages de vos équipes et des règles propres à votre activité.</p><a class="text-link" href="#techno">Choisir une base technique ↗</a></article>
      <article><span class="number">02 / ÉVOLUTION</span><h3>Faire grandir votre existant</h3><p>Ajouter une fonction, relier un nouvel outil, revoir les parcours ou préparer un changement d’échelle. Nous partons de ce qui fonctionne déjà pour identifier les évolutions utiles.</p><a class="text-link" href="/contact/">Présenter votre application ↗</a></article>
      <article class="featured-offer"><span class="number">03 / MIGRATION</span><h3>Préparer votre prochaine architecture</h3><p>Vous envisagez de quitter tout ou partie d’un environnement PC SOFT ? Notre double expertise permet d’étudier une migration vers d’autres technologies, dont C# et JavaScript, en tenant compte de votre patrimoine métier.</p><a class="text-link" href="/migration-applications-pcsoft/">Explorer la migration ↗</a></article>
    </div>
  </section>
  <section class="section migration-feature" id="double-expertise"><div><span class="eyebrow">02 / DOUBLE EXPERTISE</span><h2>Comprendre d’où vous partez.<br><em>Construire où vous allez.</em></h2><p class="large">Une migration réussie préserve ce qui rend votre logiciel utile : ses données, ses règles métier et les habitudes essentielles de vos équipes.</p><p>Notre connaissance des technologies PC SOFT nous aide à analyser l’application d’origine. Notre expertise dans d’autres langages et technologies, notamment C# et JavaScript, ouvre de nouvelles possibilités pour son évolution. Nous réunissons ces deux regards pour proposer une trajectoire adaptée à votre contexte.</p>${migrationAction}</div>
    <div class="architecture-map" role="group" aria-label="Principe d’une migration : analyser l’existant, préserver le métier, choisir la cible">
      <div class="map-node"><span class="eyebrow">VOTRE EXISTANT</span><strong>WinDev · WebDev<br>WinDev Mobile</strong><span>Applications, données, interfaces</span></div>
      <div class="map-bridge"><span aria-hidden="true">↓</span><strong>Votre métier fait le lien</strong><span>Règles · usages · continuité</span><span aria-hidden="true">↓</span></div>
      <div class="map-node map-target"><span class="eyebrow">VOTRE TRAJECTOIRE</span><strong>Des technologies adaptées<br>à votre projet</strong><span>Une cible choisie, pas imposée</span></div>
    </div>
  </section>
  <section class="section" id="techno"><div class="section-heading"><span class="eyebrow">03 / TECHNOLOGIES</span><h2>Plusieurs technologies.<br>Un même objectif métier.</h2><p>Les technologies présentées ici illustrent une partie de nos compétences. Nous choisissons les outils en fonction de votre application, de son exploitation et des compétences nécessaires pour la faire vivre.</p></div>
    <div class="technology-grid">${[
      ['WD', 'WinDev', 'Applications métier de bureau et évolution de votre parc logiciel.', '/developpement-windev/'],
      ['WB', 'WebDev', 'Applications web, portails et accès aux outils depuis un navigateur.', '/developpement-webdev/'],
      ['WM', 'WinDev Mobile', 'Applications mobiles adaptées aux usages des équipes sur le terrain.', '/developpement-windev-mobile/'],
      ['C#', 'C#', 'Applications et services sur mesure, reprise de logique métier et projets de migration.', '/developpement-csharp/'],
      ['JS', 'JavaScript', 'Interfaces web et applications conçues autour de vos parcours utilisateurs.', '/developpement-javascript/']
    ].map(([mark, title, text, href]) => `<a class="technology-card" href="${href}"><span class="tech-monogram" aria-hidden="true">${mark}</span><h3>${title}</h3><p>${text}</p><span class="text-link">En savoir plus ↗</span></a>`).join('')}</div>
  </section>
  ${databaseSection}
  <section class="section company" id="societe"><div><span class="eyebrow">05 / LA SOCIÉTÉ</span><h2>Une expertise PC SOFT.<br>Une vision ouverte.</h2>${partner}</div><div><p class="large">Serial Coders est spécialisée dans le développement d’applications sur mesure pour tous les secteurs d’activité.</p><p>Partenaire Gold de PC SOFT, nous maîtrisons WinDev, WebDev et WinDev Mobile. Nous continuons à accompagner les entreprises qui choisissent cet écosystème pour créer et faire évoluer leurs logiciels.</p><p>Nos compétences couvrent également d’autres langages et technologies, notamment C# et JavaScript. Cette complémentarité nous permet d’accompagner les entreprises qui souhaitent diversifier leur environnement technique ou préparer une migration, sans perdre la connaissance accumulée dans leur application.</p><p>Notre rôle : vous aider à prendre une décision argumentée en rapprochant les besoins métier, les contraintes techniques et le coût global de votre logiciel. Nous intervenons sur des projets en France et à l’international.</p></div></section>
  <section class="section" id="secteurs"><span class="eyebrow">06 / SECTEURS D’ACTIVITÉ</span><h2>Le point commun :<br>un métier qui vous est propre.</h2><p class="section-intro">Les exemples ci-dessous illustrent les types de besoins qu’une application sur mesure peut couvrir. Le périmètre est défini avec vos équipes, selon vos contraintes et votre activité.</p><div class="sector-grid">${[
    ['Industrie & production', 'Suivi des opérations, traçabilité et circulation des informations entre les équipes.'],
    ['Commerce & distribution', 'Gestion des commandes, des catalogues, des stocks et des échanges avec vos autres outils.'],
    ['Services & conseil', 'Suivi des dossiers, organisation des missions et partage de l’information métier.'],
    ['Logistique & interventions', 'Préparation des opérations, saisie sur le terrain et consultation de données en mobilité.'],
    ['Associations & organisations', 'Gestion des activités, des adhésions et des processus propres à votre organisation.'],
    ['Votre secteur', 'Un besoin spécifique ne rentre pas toujours dans une catégorie. Décrivez-nous votre fonctionnement.']
  ].map(([name, text], i) => `<article><span class="sector-index" aria-hidden="true">0${i+1}</span><h3>${name}</h3><p>${text}</p></article>`).join('')}</div></section>
  <section class="section process" id="methode"><span class="eyebrow">07 / MÉTHODE</span><h2>Une trajectoire lisible.<br>Des décisions à chaque étape.</h2>${steps()}</section>
  <section class="section home-faq"><div><span class="eyebrow">AVANT DE VOUS LANCER</span><h2>Les questions<br>qui comptent.</h2>${migrationAction}</div>${faq([migrationFaq[0], migrationFaq[3], migrationFaq[4]])}</section>
  <section class="contact-band" id="contact"><span class="eyebrow">PARLONS DE VOTRE PROCHAINE ÉTAPE</span><h2>Un nouveau projet ?<br><em>Faisons évoluer<br>votre métier.</em></h2><p>Création, ajout de nouveaux modules ou migration : présentez-nous votre application, vos enjeux et vos ambitions. Définissons ensemble votre prochaine étape.</p>${action('Échangeons sur votre besoin')}</section>`
};

export const migrationPage = {
  path: '/migration-applications-pcsoft/',
  title: 'Migration d’applications PC SOFT | Serial Coders',
  description: 'Préparez la migration de vos applications PC SOFT avec Serial Coders : expertise multitechnologie, audit, choix de la cible, données et bascule.',
  body: `<section class="detail-hero migration-hero"><a class="back" href="/">← Serial Coders</a><span class="eyebrow">MIGRATION D’APPLICATIONS PC SOFT</span><h1>Changer de technologie.<br><em>Préserver votre métier.</em></h1><p class="lead">Votre application WinDev, WebDev ou WinDev Mobile concentre des années de fonctionnement métier. Nous vous aidons à préparer son évolution vers les technologies adaptées à votre projet en identifiant ce qu’il faut conserver, repenser et sécuriser.</p>${action('Parlons de votre migration')}</section>
  <section class="section migration-feature"><div><span class="eyebrow">UN CHOIX D’ENTREPRISE</span><h2>Pourquoi envisager<br>une migration ?</h2><p>Votre contexte évolue : nouveaux usages, besoin d’interopérabilité, compétences disponibles ou recherche d’une meilleure visibilité sur les coûts. La technologie choisie hier mérite parfois d’être réévaluée.</p><p>Les conditions de licence et de déploiement font partie de cette réflexion. Nous examinons avec vous les conditions applicables à votre projet, le nombre d’utilisateurs, les perspectives de croissance et les coûts d’exploitation. L’objectif est de comparer des scénarios réalistes, pas de remplacer un outil par principe.</p><p>Maintenir, moderniser ou migrer : chaque option doit être évaluée au regard de ce qu’elle apporte à votre entreprise.</p></div>${figure()}</section>
  <section class="section company"><div><span class="eyebrow">NOTRE ATOUT</span><h2>La connaissance<br>des deux environnements.</h2>${partner}</div><div><p class="large">Comprendre l’application d’origine est aussi important que maîtriser la technologie cible.</p><p>Notre expertise PC SOFT permet d’aborder les traitements, les écrans et les dépendances de votre existant avec les bons repères. Notre expertise multitechnologie, qui comprend notamment C# et JavaScript, permet d’envisager une autre architecture et de réimplémenter les fonctions qui comptent.</p><p>Nous restons partenaire Gold de PC SOFT. Une migration est un choix lié à votre contexte ; elle ne remet pas en cause la pertinence de cet écosystème pour d’autres projets.</p></div></section>
  <section class="section"><span class="eyebrow">LA MÉTHODE</span><h2>De l’état des lieux<br>à une bascule préparée.</h2>${steps()}</section>
  <section class="section scenario-section"><span class="eyebrow">TROIS TRAJECTOIRES À COMPARER</span><h2>Il n’y a pas qu’une façon<br>de faire évoluer un logiciel.</h2><div class="offer-grid"><article><h3>Conserver et optimiser</h3><p>Lorsque l’application répond au besoin, des évolutions ciblées peuvent être plus pertinentes qu’une réécriture. Nous examinons les limites réelles avant de proposer un changement de socle.</p></article><article><h3>Migrer progressivement</h3><p>Remplacer un module ou ouvrir une interface permet parfois de répartir l’effort. La coexistence exige une gestion explicite des données, des échanges et des responsabilités de chaque composant.</p></article><article><h3>Reconstruire le périmètre</h3><p>Une nouvelle base peut se justifier lorsque les contraintes s’accumulent. Le périmètre utile, les données à reprendre et les critères de recette doivent alors être définis avant la réalisation.</p></article></div></section>
  <section class="section detail-grid"><div><span class="eyebrow">UNE DÉCISION DOCUMENTÉE</span><h2>Comparer le coût total,<br>pas seulement les licences.</h2><p>Les coûts varient selon la version, les contrats, l’architecture et les composants retenus. Aucun montant ni gain n’est présumé avant l’étude.</p></div><ul class="needs"><li><strong>Investissement initial :</strong> analyse, développement, reprise des données et validation.</li><li><strong>Coûts récurrents :</strong> licences applicables, hébergement, maintenance et exploitation.</li><li><strong>Transition :</strong> coexistence, accompagnement des utilisateurs et éventuelles interruptions.</li><li><strong>Durée de vie :</strong> facilité d’évolution, disponibilité des compétences et dépendances techniques.</li></ul></section>
  <section class="section"><div class="section-heading"><span class="eyebrow">LES POINTS À SÉCURISER</span><h2>Votre activité continue.<br>La migration doit en tenir compte.</h2></div><div class="sector-grid"><article><h3>Les règles métier</h3><p>Recenser les cas particuliers et les traitements essentiels pour éviter qu’une nouvelle interface masque une régression fonctionnelle.</p></article><article><h3>Les données</h3><p>Préparer les correspondances, les contrôles de cohérence et les reprises à blanc avant de déplacer des informations en production.</p></article><article><h3>Les interfaces</h3><p>Identifier les échanges avec les autres logiciels, les fichiers, les services et les équipements qui dépendent de l’application.</p></article><article><h3>La recette</h3><p>Définir avec vos utilisateurs des scénarios représentatifs et des critères d’acceptation vérifiables.</p></article><article><h3>La bascule</h3><p>Planifier la mise en service, les sauvegardes, les éventuelles fenêtres d’intervention et un scénario de retour arrière.</p></article><article><h3>La transmission</h3><p>Préparer les éléments de documentation et les modalités de maintenance pour faire vivre le logiciel après la migration.</p></article></div></section>
  <section class="section home-faq"><div><span class="eyebrow">QUESTIONS FRÉQUENTES</span><h2>Préparer le projet<br>sans idée préconçue.</h2></div>${faq(migrationFaq)}</section>
  <section class="contact-band"><span class="eyebrow">LE PREMIER ÉCHANGE</span><h2>Décrivez-nous votre existant.</h2><p>Technologies et versions utilisées, nombre d’utilisateurs, interfaces, difficultés rencontrées et objectifs : ces éléments nous aideront à cadrer la discussion.</p>${action('Étudier mon projet de migration')}</section>`
};

export const newTechnologyPages = [
  {
    path: '/developpement-csharp/', title: 'Développement C# sur mesure & migration | Serial Coders',
    description: 'Serial Coders développe vos applications et services en C# et accompagne la migration de votre logique métier depuis un environnement PC SOFT.',
    body: `<section class="detail-hero"><a class="back" href="/#techno">← Nos technologies</a><span class="eyebrow">DÉVELOPPEMENT C#</span><h1>Une autre base technique.<br><em>Toujours votre métier.</em></h1><p class="lead">Nous développons en C# pour créer des applications sur mesure, faire évoluer votre système d’information ou reconstruire un périmètre métier issu d’une application PC SOFT.</p>${action()}</section><section class="section detail-grid"><div><h2>Du besoin fonctionnel<br>à l’architecture.</h2><p>Le choix de C# prend son sens lorsqu’il répond aux usages, aux interfaces et aux conditions d’exploitation de votre projet.</p></div><ul class="needs"><li>Concevoir une application adaptée à vos processus internes.</li><li>Développer des services qui structurent et exposent votre logique métier.</li><li>Reprendre des traitements existants avec des critères de validation explicites.</li><li>Préparer une maintenance et des évolutions cohérentes avec votre organisation.</li></ul></section><section class="section company"><div><span class="eyebrow">DE WINDEV À C#</span><h2>Transmettre la logique.<br>Repenser l’implémentation.</h2></div><div><p class="large">Migrer une application ne consiste pas à transcrire ses lignes de code.</p><p>Nous identifions les règles métier, les dépendances, les échanges et les besoins des utilisateurs avant de définir la structure cible. Certains parcours peuvent être conservés, d’autres repensés. Les tests et la recette doivent vérifier que le résultat attendu reste au rendez-vous.</p>${migrationAction}</div></section><section class="section"><h2>Les décisions à prendre ensemble.</h2><div class="offer-grid"><article><h3>Les usages</h3><p>Application de bureau, service ou composant d’un système plus large : préciser le rôle du logiciel avant de choisir son architecture.</p></article><article><h3>Les données et interfaces</h3><p>Étudier les échanges, les accès, les formats et la reprise des informations indispensables à l’activité.</p></article><article><h3>L’exploitation</h3><p>Définir l’hébergement, la maintenance, les composants nécessaires et leurs conditions d’utilisation.</p></article></div></section><section class="contact-band"><h2>Un projet C# à construire<br>ou une migration à préparer ?</h2>${action()}</section>`
  },
  {
    path: '/developpement-javascript/', title: 'Développement JavaScript sur mesure | Serial Coders',
    description: 'Applications web et interfaces métier en JavaScript : Serial Coders accompagne vos développements sur mesure et vos projets de migration PC SOFT.',
    body: `<section class="detail-hero"><a class="back" href="/#techno">← Nos technologies</a><span class="eyebrow">DÉVELOPPEMENT JAVASCRIPT</span><h1>Vos usages métier.<br><em>Une expérience web adaptée.</em></h1><p class="lead">Nous utilisons JavaScript pour concevoir des interfaces et des applications web sur mesure, en lien avec les services et les données de votre système d’information.</p>${action()}</section><section class="section detail-grid"><div><h2>Faire du navigateur<br>un outil de travail.</h2><p>L’enjeu est de rendre les parcours utiles, compréhensibles et adaptés aux contextes d’utilisation.</p></div><ul class="needs"><li>Créer des interfaces de consultation et de saisie adaptées à vos équipes.</li><li>Construire un portail autour d’un processus propre à votre activité.</li><li>Relier une interface aux services et aux données nécessaires à son fonctionnement.</li><li>Repenser des parcours existants dans le cadre d’une migration vers le Web.</li></ul></section><section class="section company"><div><span class="eyebrow">MIGRATION & MODERNISATION</span><h2>Revoir l’interface.<br>Respecter le fonctionnement métier.</h2></div><div><p class="large">Une nouvelle interface doit s’intégrer à une architecture cohérente.</p><p>Nous étudions la répartition entre les traitements exécutés dans le navigateur et les services côté serveur, les droits d’accès, les échanges de données et les situations d’erreur. Notre connaissance de l’existant PC SOFT permet de replacer ces choix dans le fonctionnement de votre application.</p>${migrationAction}</div></section><section class="section"><h2>Un projet web se prépare<br>au-delà de ses écrans.</h2><div class="offer-grid"><article><h3>Les parcours</h3><p>Identifier les tâches prioritaires, les utilisateurs et les appareils utilisés pour concevoir une interface adaptée.</p></article><article><h3>Les échanges</h3><p>Définir les interfaces avec vos données et les autres applications, ainsi que les droits associés.</p></article><article><h3>La pérennité</h3><p>Choisir les bibliothèques et composants en considérant leur maintenance, leurs licences et les compétences nécessaires.</p></article></div></section><section class="contact-band"><h2>Votre prochain outil métier<br>sera-t-il accessible sur le Web ?</h2>${action()}</section>`
  }
];

export function enrichExistingService(page) {
  const content = {
    '/developpement-windev/': ['WinDev', 'Les écrans de saisie, les traitements, les éditions et les échanges avec vos autres outils forment un ensemble. Nous étudions les usages quotidiens pour distinguer les fonctions indispensables, les tâches répétitives et les points de friction.', 'Des règles de validation aux traitements de données, les particularités de votre activité doivent être explicites et vérifiables. Nous préparons avec vos équipes les scénarios qui permettront de valider l’application.'],
    '/developpement-webdev/': ['WebDev', 'Un portail ou une application web doit prendre en compte plusieurs profils d’utilisateurs, leurs droits et les informations auxquelles ils accèdent. Le cadrage porte autant sur les parcours que sur les échanges avec le système d’information.', 'Nous examinons les accès, les validations, les situations d’erreur et les conditions de déploiement. La recette s’appuie sur des scénarios métier représentatifs, avec les personnes qui utiliseront l’application.'],
    '/developpement-windev-mobile/': ['WinDev Mobile', 'Une utilisation sur le terrain impose des choix concrets : taille d’écran, conditions de saisie, qualité du réseau, appareils et informations à consulter. Le besoin de fonctionnement hors connexion, s’il existe, doit être étudié dès le départ.', 'Nous définissons avec vous les échanges avec le système d’information et les comportements attendus lorsque le réseau ou une donnée manque. Les tests doivent refléter les conditions d’utilisation réelles.']
  }[page.path];
  if (!content) return page;
  const [technology, usage, validation] = content;
  const extra = `<section class="section"><span class="eyebrow">DÉVELOPPEMENT SUR MESURE</span><h2>Le fonctionnement métier<br>guide les choix techniques.</h2><div class="editorial-columns"><p>${usage}</p><p>${validation}</p></div></section><section class="section company"><div><span class="eyebrow">PARTENAIRE GOLD PC SOFT</span><h2>Faire évoluer ${technology}.<br>Ou préparer une autre voie.</h2>${partner}</div><div><p class="large">Nous accompagnons votre projet dans l’écosystème PC SOFT comme dans une réflexion de migration.</p><p>Votre stratégie, vos besoins d’intégration ou vos coûts d’exploitation évoluent ? Nous pouvons étudier le maintien de l’existant, une modernisation progressive ou une migration vers d’autres technologies, notamment C# et JavaScript. Le choix repose sur votre contexte, vos contraintes et le périmètre réellement utile.</p>${migrationAction}</div></section>`;
  return {...page, body: page.body.replace('<section class="contact-band">', `${extra}<section class="contact-band">`)};
}
